apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bgd-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /bgd(/|$)(.*)
        backend:
          service:
            name: bgd
            port:
              number: 80
