apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # This is the name of kind `Secret` create by External Secrets allow application get data
  name: secret-from-conjur
spec:
  refreshInterval: 10s
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: conjur
    kind: SecretStore
  data:
  - secretKey: secret00
    remoteRef:
      key: BotApp/secretVar
